apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: esxi-exporter
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: esxi-exporter
  jobLabel: job
  endpoints:
  - port: metrics
    interval: 60s